pipeline {
    agent  {
        docker {
            image 'maven'
            args '-v /Users/russellanson/.m2:/root/.m2'
        }
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/woorak/maven.git'
            }
        }
        
        stage('Build') {
            steps {
                sh '''
                    mvn clean package
                '''
            }
        }
    }
}