
    
    
    
                docker.image('maven:3-eclipse-temurin-11').inside {
                    git branch: 'main', url: 'https://github.com/woorak/maven.git'
                    sh """
                        mvn -B clean package
                        ls -l target
                    """
                }
